### PR TITLE
Remove forced debug enablement (issue #6)

### PR DESCRIPTION
**Pull request by akoptelov**
@mikhail-angelov I guess debug output is only intended for debugging, not for production use (i.e. in context of other tests)?

### CODE REVIEW

**Comment by mikhail-angelov** [comment]
Hi, I agree, this code needs to be changed, but verbose option should be there even on release, it helps to investigate problems

**Comment by akoptelov** [comment]
@mikhail-angelov totally agree with you, but I'm not sure logging should be turned on by your library but by user running test.

**Comment by mikhail-angelov** [comment]
>but I'm not sure logging should be turned on by your library but by user running test.
I did it on purpose, it's more clear if lib has explicit option to enable logs, otherwise, it will take too much time to understand how to enable logs at this lib or especially at dependent libs.

**Comment by akoptelov** [comment]
With the current implementation calling `Debug.enable('mongo-unit')` turns off other debug output, and `Debug.enable('*')` makes output so bloated that it is completely useless.
Do you think of some simple way to turn on debugging for both your library and mongo?

**Comment by mikhail-angelov** [comment]
>Do you think of some simple way to turn on debugging for both your library and mongo?
I personally do not like Debug.enable API it's hard to find how to enable particular debug without search all over source code (including npm packages)
but mongodb-prebuilt use it

so to enable logs just for mongodb-prebuilt, good enough solution will be


  if(mongo_opts.verbose){
    Debug.enable('mongo-unit')
    Debug.enable('mongodb-download-MongoDBDownload')
    Debug.enable('mongodb-download-MongoDBPlatform')
    Debug.enable('mongodb-prebuilt-MongoBins')
    Debug.enable('mongodb-prebuilt-MongodHelper')
    Debug.enable('mongodb-prebuilt-MongoSupervice')
    Debug.enable('mongodb-prebuilt-MongodHelper')
//... maybe I misses something
  }

**Comment by Y0hy0h** [comment]
It appears that you can simplify the enable using [wildcards](https://www.npmjs.com/package/debug#wildcards):
```
Debug.enable('mongo-unit')
Debug.enable('mongodb*')
```

I have not tested this, however.

**Comment by sarneeh** [comment]
Any news on this? It bloats test outputs a little 😭

**Comment by mikhail-angelov** [comment]
@sarneeh it should not provide any debug logs if you disable `verbose` option

**Comment by sarneeh** [comment]
@mikhail-angelov I'd like to get rid of the `mongo-unit mongo is started on mongodb://localhost:27017/test` log message. Turning `verbose` to false doesn't make it dissappear.

**Comment by akoptelov** [comment]
@mikhail-angelov I still think that debug output should be controlled using environment variable instead of option passed in the test code. Users would get more freedom on which module they want to debug.

**Comment by mikhail-angelov** [comment]
@sarneeh 
>I'd like to get rid of the mongo-unit mongo is started on 

this one is just fixed on 1.3.4

**Comment by mikhail-angelov** [comment]
@akoptelov 
> I still think that debug output should be controlled using environment variable instead of option passed in the test code. Users would get more freedom on which module they want to debug.

I maybe you are right, I do not have strong thoughts about it
BTW you can use Debug API even if `verbose` is turned off
and it turned off by default

**Pull request closed without merging**
