### PR TITLE
Clean up root

### PR DESCRIPTION
**Pull request by Y0hy0h**
The root was missing a [lockfile](https://yarnpkg.com/lang/en/docs/yarn-lock/) which is necessary to reliably reproduce installs.

Additionally, the debug log was removed, as it doesn't contribute useful information to the project.

### CODE REVIEW

**Comment by sesm** [comment]
I'm not sure if it's correct to add `yarn.lock` to the project. Could you please provide an example of open source library that does it?
Maybe it's better to pin version numbers in `package.json`?

**Comment by Y0hy0h** [comment]
You can read it up in the [yarn doc](https://yarnpkg.com/lang/en/docs/yarn-lock/#toc-check-into-source-control).

I prefer yarn over npm, that's why I contributed the `yarn.lock`. If you prefer npm, you can simply upload the [`package.lock`](https://docs.npmjs.com/files/package-lock.json#description) alongside or instead of the `yarn.lock`. But this file is supposed be tracked in the VCS.

As far as I understand, it's different from pinning the dependencies in the `package.json`. The reason I see is that the `package.json` should declare which versions are compatible, whereas the lockfile is there to keep track of what versions where installed and thus tested with.

**Comment by mikhail-angelov** [comment]
I'm not sure yarn.lock is needed

**Comment by Y0hy0h** [comment]
Have you read the documentation for [`yarn.lock`](https://yarnpkg.com/lang/en/docs/yarn-lock/#toc-check-into-source-control) and [`package.lock`](https://docs.npmjs.com/files/package-lock.json#description)?

**Comment by Y0hy0h** [comment]
This is your repo, I'm fine if you decide not to include it. I just wanted to make sure you have read what it is meant for. ;)

**Comment by sesm** [comment]
I think the downside of introducing `yarn.lock`, is that it has to be kept up-to-date, which is problematic, if the primary developer prefers not to use yarn.
As far as I can tell from documentation on yarn website, adding `yarn.lock` does not affect the users of the library. 
To reliably reproduce installs, the users of the library should introduce `yarn.lock` or `package-lock.json` in their respective projects.

**Comment by Y0hy0h** [comment]
> it has to be kept up-to-date

Yarn and npm keep it up to date automatically on installs where the packages changed. You only need to commit it, when it changed.

> To reliably reproduce installs, the users of the library should introduce yarn.lock or package-lock.json in their respective projects.

I see no way without a lockfile. How would they do that?

That being said, I agree that if you prefer npm, it makes more sense to commit the `package.lock` instead of `yarn.lock`. And it's also ok to just decide to not include them. I just have a slight feeling that I didn't explain the use of the lockfile well enough. ;)

**Comment by mikhail-angelov** [comment]
>I just wanted to make sure you have read what it is meant for. ;)

@Y0hy0h, you make me read it :)

> Current package only
During install Yarn will only use the top-level yarn.lock file and will ignore any yarn.lock files that exist within dependencies. The top-level yarn.lock file includes everything Yarn needs to lock the versions of all packages in the entire dependency tree.

so it means this lock file will be ignored if user run 
`yarn install` on his app
so it make less sense of this file

**Comment by Y0hy0h** [comment]
> so it means this lock file will be ignored if user run `yarn install` on his app

That is correct. The lockfile is intended for the developers of this project.  
I guess you don't really need it right now. If you encounter any issues à la "works on my machine", then try to remember this. ;)

I think in general it's a good idea to just commit it. But I understand that there is currently no problem that would be resolved with it, so I'll close this issue. :+1:

**Pull request closed without merging**
